export const FEED_ACTION_TYPES = {
  // Feed Object
  ADD_FEED: 'ADD_FEED',
  DELETE_FEED: 'DELETE_FEED',
  EDIT_FEED: 'EDIT_FEED',
  GET_FEED: 'GET_FEED',

  // Feed Data
  REFESH_FEED_DATA: 'REFESH_FEED_DATA'
};

export const FEED_DATA_ACTION_TYPES = {
  REQUEST_FEED: 'REQUEST_FEED',
  RECEIVE_FEED: 'RECEIVE_FEED',
  INVALIDATE_FEED: 'INVALIDATE_FEED'
};


export const FEED_ITEM_ACTION_TYPES = {
  SHARE: 'SHARE',
  TOGGLE_HIDDEN: 'TOGGLE_HIDDEN',
  TOGGLE_READ: 'TOGGLE_READ',
  TOGGLE_STARRED: 'TOGGLE_STARRED'
};
